sudo: required

services:
  - docker

language: java
jdk:
  - openjdk8

install: gradle wrapper --gradle-version 4.9
script:
  - sudo mkdir -p build/jacoco/output &&
    sudo touch build/jacoco/output/jacoco.exec &&
    sudo chmod -Rf 0777 build &&
    make install &&
    make check
  - ls -lha build/jacoco/output

after_success:
  - bash <(curl -s https://codecov.io/bash)