sudo: required

services:
- docker

language: java
jdk:
  - openjdk8

install: gradle wrapper --gradle-version 4.9
script:
  - make install && make &&
    prepare-check &&
    mkdir -p build/jacoco/output && chmod 0777 build/jacoco/output &&
    ./gradlew check