version: '3'

services:
  db:
    image: mysql:5.5.51
    environment:
      - MYSQL_DATABASE=vermietet
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 13000:3306
    volumes:
      - ./setup/schema.sql:/docker-entrypoint-initdb.d/schema.sql