version: '3'

services:
  db:
    image: mysql:5.5.51
    environment:
      - MYSQL_DATABASE=vermietet
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 13000:3306
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  app_test:
    image: openjdk:8-jdk-alpine
    environment:
      - JDBC_URL=jdbc:mysql://db_test:3306/vermietet
      - JDBC_USERNAME=root
      - JDBC_PASSWORD=
      - GRADLE_USER_HOME=/usr/src/vermietet/.gradle-test
      - GRADLE_HOME=/usr/src/vermietet/.gradle-test
    ports:
      - 13002:8080
      - 13003:6300
    volumes:
      - ./:/usr/src/vermietet
      - ./jacoco:/jacoco
    working_dir: /usr/src/vermietet
    command: ./gradlew -PjvmArgs="-javaagent:/jacoco/jacocoagent.jar=output=tcpserver,address=*,includes=vermietet.*,destfile=build/jacoco/output/jacoco.exec,classdumpdir=build/jacoco/output/classdump" -Dorg.gradle.project.buildDir=/usr/src/vermietet/build-test -Dgradle.user.home=/usr/src/vermietet/.gradle-test --project-cache-dir=/usr/src/vermietet/.gradle-test bootRun
    depends_on:
      - db_test
  db_test:
    image: mysql:5.5.51
    environment:
      - MYSQL_DATABASE=vermietet
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 13001:3306
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro