version: '3'

services:
  app:
    image: gradle:4.10.2-jdk
    environment:
      - JDBC_URL=jdbc:postgresql://db:5432/vermietet
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=mysecretpassword
    ports:
      - 13000:8080
      - 13002:5005
    volumes:
      - .:/app
    working_dir: /app
    command: gradle -PjvmArgs="-javaagent:/app/jacoco/jacocoagent.jar=output=tcpserver,address=*,includes=vermietet.*,destfile=build/jacoco/output/jacoco.acceptanceTest.exec,classdumpdir=build/jacoco/output/classdump -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005" bootRun
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_DB=vermietet
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d:ro
    ports:
      - 13001:5432